version: 2
jobs:
  build-build-build-build-build-build-build:
    docker:
      - image: golang:1.8
    working_directory: /tmp/sample-repo
    resource_class: small
    steps:
      - checkout
      - run:
          name: stderr routing
          command: |
            ls -lha
            pwd
            >&2 echo "this should go to stderr"
      - run:
          name: stdout routing
          command: |
            echo "this should go to stdout"
            >&2 echo "then this should go to stderr"
            echo "this final line goes to stdout"
  test-test-test-test-test-test-test-test:
    docker:
      - image: golang:1.8
    resource_class: small
    working_directory: /tmp/sample-repo
    steps:
      - checkout
      - run:
          name: foo
          command: echo foo

workflows:
  version: 2
  build:
    jobs:
      - build-build-build-build-build-build-build
      - approve-approve-approve-approve-approve-approve:
          type: approval
          requires:
            - build-build-build-build-build-build-build
      - test-test-test-test-test-test-test-test:
          requires:
            - approve-approve-approve-approve-approve-approve
