version: 2
jobs:
  successful-one:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: /tmp/sample-repo
    resource_class: small
    steps:
      - run:
          command: echo 'hi'
  build-build-build-build-build-build-build:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: /tmp/sample-repo
    resource_class: small
    steps:
      - run:
          command: sleep 300
      - run:
          name: stderr routing
          command: |
            ls -lha
            pwd
            >&2 echo "this should go to stderr"
      - run:
          name: stdout routing
          command: |
            echo "this should go to stdout"
            >&2 echo "then this should go to stderr"
            echo "this final line goes to stdout"
  test-test-test-test-test-test-test-test:
    docker:
      - image: circleci/clojure:lein-2.7.1
    resource_class: small
    working_directory: /tmp/sample-repo
    steps:
      - run:
          name: foo
          command: echo foo

workflows:
  version: 2
  build:
    jobs:
      - successful-one
      - test-test-test-test-test-test-test-test:
          requires:
            - successful-one
